name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}

      - uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Create .gpg key
        run: |
          echo $GPG_KEY_ARMOR | base64 --decode > ./release.asc
          gpg --quiet --output $GITHUB_WORKSPACE/release.gpg --dearmor ./release.asc

          echo "Build and publish"
          sed -i -e "s,mavenCentralUsername=,mavenCentralUsername=$SONATYPE_TOKEN_USERNAME,g" gradle.properties
          SONATYPE_TOKEN_PASSWORD_ESCAPED=$(printf '%s\n' "$SONATYPE_TOKEN_PASSWORD" | sed -e 's/[\/&]/\\&/g')
          sed -i -e "s,mavenCentralPassword=,mavenCentralPassword=$SONATYPE_TOKEN_PASSWORD_ESCAPED,g" gradle.properties
          sed -i -e "s,signing.keyId=,signing.keyId=$GPG_KEY_ID,g" gradle.properties
          sed -i -e "s,signing.password=,signing.password=$GPG_PASSWORD,g" gradle.properties
          sed -i -e "s,signing.secretKeyRingFile=,signing.secretKeyRingFile=$GITHUB_WORKSPACE/release.gpg,g" gradle.properties

        env:
          GPG_KEY_ARMOR: ${{ secrets.SYNCED_GPG_KEY_ARMOR }}
          GPG_KEY_ID: ${{ secrets.SYNCED_GPG_KEY_ID }}
          GPG_PASSWORD: ${{ secrets.SYNCED_GPG_KEY_PASSWORD }}
          SONATYPE_TOKEN_PASSWORD: ${{ secrets.SONATYPE_TOKEN_PASSWORD }}
          SONATYPE_TOKEN_USERNAME: ${{ secrets.SONATYPE_TOKEN }}

      - name: Publish to MavenCentral
        run: ./gradlew publishToMavenCentral --warn --stacktrace